name: chef_buddy
description: A new Flutter project.

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  google_fonts: ^6.2.1
  english_words: ^4.0.0

  # Firebase core + auth
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

  # ✅ Required for Firebase Web (fixes PromiseJsImpl errors)
  firebase_core_web: ^2.12.0
  firebase_auth_web: ^5.8.13
  js: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: WinkyRough
      fonts:
        - asset: assets/fonts/WinkyRough-VariableFont_wght.ttf
