// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjgvYazwkV3RCBLar8MsyJQAYqwkZz6Ms',
    appId: '1:860706500061:web:0dbbece76191b84e119a34',
    messagingSenderId: '860706500061',
    projectId: 'chefbuddy-94681',
    authDomain: 'chefbuddy-94681.firebaseapp.com',
    storageBucket: 'chefbuddy-94681.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvPeS4SW_Dqa8WdjYjIxTF8CuT7wCVAkg',
    appId: '1:860706500061:android:9b3063492c69fb7a119a34',
    messagingSenderId: '860706500061',
    projectId: 'chefbuddy-94681',
    storageBucket: 'chefbuddy-94681.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1n15Cvpa9cHi-02sKTfKiXbE6SwC9ids',
    appId: '1:860706500061:ios:c6eac8265be83d30119a34',
    messagingSenderId: '860706500061',
    projectId: 'chefbuddy-94681',
    storageBucket: 'chefbuddy-94681.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1n15Cvpa9cHi-02sKTfKiXbE6SwC9ids',
    appId: '1:860706500061:ios:c6eac8265be83d30119a34',
    messagingSenderId: '860706500061',
    projectId: 'chefbuddy-94681',
    storageBucket: 'chefbuddy-94681.firebasestorage.app',
    iosBundleId: 'com.example.namerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjgvYazwkV3RCBLar8MsyJQAYqwkZz6Ms',
    appId: '1:860706500061:web:aa9c296a9f02752e119a34',
    messagingSenderId: '860706500061',
    projectId: 'chefbuddy-94681',
    authDomain: 'chefbuddy-94681.firebaseapp.com',
    storageBucket: 'chefbuddy-94681.firebasestorage.app',
  );
}
